name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Works with Node 20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Works with Node 20
        with:
          node-version: '20'

      - name: Inject environment variables
        run: |
          echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_REACT_APP_FIREBASE_API_KEY: ${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist